### ISSUE TITLE
refused to build on rocky 8 and rhel 8

### ISSUE THREAD

**Issue by ruben-herold** [karljohns0n/pkg-libmodsecurity#3]
hi,

this wil not build on a plain Rocky 8 or RHEL 8 cause the included libmaxminddb-devel is to old. 
Fixed with #1

**Comment by karljohns0n** [comment]
Thanks for the PR, merged, built, and available in testing repo.
Tested with nginx [here](https://github.com/karljohns0n/nginx-more/commit/223a1c3a6d27359e5c0ad023ff0d6df209bae128).
